// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJt4spMg6Qd2oXY0qnIAl2sBt_yOE2Vw4',
    appId: '1:478258864520:web:baaa71932f5459dc879a3d',
    messagingSenderId: '478258864520',
    projectId: 'pushhnoti',
    authDomain: 'pushhnoti.firebaseapp.com',
    storageBucket: 'pushhnoti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaHh-Jm0kmkNOnWWZcVP7ac_II-4m7WKk',
    appId: '1:478258864520:android:62536b00a212882c879a3d',
    messagingSenderId: '478258864520',
    projectId: 'pushhnoti',
    storageBucket: 'pushhnoti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2ha-6G5NDmeUtp_qvFFhuSJWV3yZ2O4',
    appId: '1:478258864520:ios:8f33d17ced7b1a76879a3d',
    messagingSenderId: '478258864520',
    projectId: 'pushhnoti',
    storageBucket: 'pushhnoti.appspot.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2ha-6G5NDmeUtp_qvFFhuSJWV3yZ2O4',
    appId: '1:478258864520:ios:de88f10f03e0c897879a3d',
    messagingSenderId: '478258864520',
    projectId: 'pushhnoti',
    storageBucket: 'pushhnoti.appspot.com',
    iosBundleId: 'com.example.smartHome.RunnerTests',
  );
}
